export const menu = {
  DASHBOARD: 'dashboard',
  DASHBOARD_YEARLY: 'Dashboard Yearly',
  DASHBOARD_DAILY: 'Dashboard Daily',
  DASHBOARD_WEEKLY: 'Dashboard Weekly',
  DASHBOARD_MONTHLY: 'Dashboard Monthly',
  TRANSACTIONS: 'transactionsOverview',
  PAYMENT_PAGES: 'paymentPage',
  MERCHANT_PAYOUTS: 'merchantPayouts',
  VAS_PROCESSED: 'VASProcessed',
  FEE_REPORTS: 'FEEReports',
  SETTINGS: 'settings',
  MY_PAYOUTS: 'My Payouts',
  MERCHANT_OVERVIEW: 'merchantOverview',
  PROXYPAY_REPORTS: 'ProxyPay Reports',
  PROXYPAY_SUBSCRIBERS: ' Subscribers',
  PROXYPAY_TRANSACTIONS: 'Transactions',
  PROXYPAY_VOLUMES: 'Volumes',
  PROXYPAY_OVERVIEW: 'Overview',
  PAYOUTS: 'payouts',
};

export const menuHeadings = {
  DASHBOARD: 'dashboard',
  PAYMENTS: 'payments',
  COMMERCE: 'commerce',
  REPORTS: 'reports',
  CONFIGURATION: 'configurations',
  PAYOUTS: 'payouts',
};
