export const path = {
  home: '/',
  dashboardMain: '/dashboard/main',
  dashboardDaily: '/dashboard/daily',
  dashboardWeekly: '/dashboard/weekly',
  dashboardMonthly: '/dashboard/monthly',
  tranasctions: '/transactions',
  paymentPages: '/payment-pages',
  page: '/page',
  login: '/auth/login',
  pay: '/pay',
  example: '/example-pay',
  payment: '/payment',
  myPayouts: '/my-payouts',
  merchantsOverview: '/merchants-overview',
  vasProcessed: '/vas-processed',
  merchantPayouts: '/merchants-payouts',
  settings: '/settings',
  feeReports: '/fee-reports',
  proxyPaySubscribers: '/proxypay-subscribers',
  proxyPayTransactions: '/proxypay-transactions',
  proxyPayVolumes: '/proxypay-volumes',
  proxyPayOverview: '/proxypay-overview',
};
