export const path = {
  home: '/',
  tranasctions: '/transactions',
  paymentPages: '/payment-pages',
  page: '/page',
  login: '/auth/login',
  pay: '/pay',
  example: '/example-pay',
  payment: '/payment',
  myPayouts: '/my-payouts',
  merchantsOverview: '/merchants-overview',
  vasProcessed: '/vas-processed',
  merchantPayouts: '/merchants-payouts',
  settings: '/settings',
};
